name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  integration:
    name: Integration
    uses: ./.github/workflows/integration.yml

  publish:
    name: Publish
    needs:
      - integration
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Get pnpm Version'
        id: pnpm-version
        run: |
          PNPM_VERSION=$(cat package.json | jq --raw-output '.packageManager' | awk -F'@' '{print $2}')
          echo "PNPM_VERSION=$PNPM_VERSION" >> $GITHUB_OUTPUT

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.pnpm-version.outputs.PNPM_VERSION }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Publish
        run: pnpm publish --no-git-checks
        working-directory: packages/starlight-package-managers
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Generate changelog
        uses: hideoo/changelogithub-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
